// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zawodnicy.Infrastructure.Repositories;

namespace Zawodnicy.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Zawodnicy.Core.Domain.Trener", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataUr")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trener");
                });

            modelBuilder.Entity("Zawodnicy.Core.Domain.Zawodnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataUr")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrenerId")
                        .HasColumnType("int");

                    b.Property<double>("Waga")
                        .HasColumnType("float");

                    b.Property<double>("Wzrost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TrenerId");

                    b.ToTable("Zawodnik");
                });

            modelBuilder.Entity("Zawodnicy.Core.Domain.Zawodnik", b =>
                {
                    b.HasOne("Zawodnicy.Core.Domain.Trener", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerId");

                    b.Navigation("Trener");
                });
#pragma warning restore 612, 618
        }
    }
}
